# build script for dedis/crypto libraries
env:
    global:
        - REPO="dedis/crypto"
        - HOME="/home/travis"
        - GOPATH="$HOME"
        - PATH="$HOME/bin:$PATH"
before_install:
    - mkdir -p $HOME/src/github.com/dedis
    - mkdir -p $HOME/bin
    - ls $TRAVIS_BUILD_DIR
    - mv $TRAVIS_BUILD_DIR $HOME/src/github.com/dedis
    - cd $HOME/src/github.com/dedis/crypto
    - go list -f '{{join .Deps "\n"}}' ./... | grep -v "^github.com/dedis/crypto" | xargs go get -t -v
before_script:
    - git remote add production https://github.com/DeDiS/crypto.git
    - git fetch -a production
    - go get github.com/dyv/dedis-ci-script
script: dedis-ci-script
